---
- name: enable httpd
  service:
    name: httpd
    enabled: true
- name: restart httpd
  service:
    name: httpd
    state: restarted
    enabled: yes
  register: restart
  listen: 'restart httpd'
- name: debug
  ansible.builtin.debug:
    msg:
    - "Handler running"